### ISSUE TITLE
Values of loudness levels

### ISSUE THREAD

**Issue by afonchikk** [Eomys/MoSQITo#36]
1. The values of loudness levels of the signals with the sound pressure levels of 20, 40, 60, and 80 dB and 1000 Hz frequency calculated by comp_loudness is not exactly equal to 20, 40, 60, and 80.    

![image](https://user-images.githubusercontent.com/34264612/153986417-118c0921-ed19-4354-bc92-edfd3d0759af.png)

2. The codes for the total loudness ignore the coefficient of 0.5. (Page 11 of ECMA-418-2 1st Edition / December 2020)

![image](https://user-images.githubusercontent.com/34264612/153986527-ca01ecaa-b1e1-4249-84ba-cee738332349.png)

**Comment by mglesser** [comment]
Hi, thanks for your interest in Mosqito. 

1. There is indeed something that is not completely obvious in the standard about the absolute loudness level. Surprisingly, the validation process proposed in the standard only check for the relative loudness levels. I guess that we should have a kind of normalization of the loudness levels at 1000 Hz. But I don't know yet how to implement that, especially when dealing with non tonal signals. If you have any expertise, your help would be welcome.
2. You're absolutely right, I'll fix it.

**Comment by afonchikk** [comment]
1. The Mosqito algorithm uses the same data block for all frequency bands.
2. There are many zeros in the first four segments of data in the segmentation algorithm, resulting in the first five numbers of low-frequency data and high-frequency data can not be used.

![image](https://user-images.githubusercontent.com/34264612/154929219-157ccdf4-efe9-4084-b25d-da92985c86aa.png)
![image](https://user-images.githubusercontent.com/34264612/154929301-b5aa71c7-d365-4f03-81cd-359cefc8af8c.png)
![image](https://user-images.githubusercontent.com/34264612/154929643-33c1c500-e5bb-4aa8-bd73-10c8543867d4.png)
![image](https://user-images.githubusercontent.com/34264612/154929711-8f20f58a-8845-42ff-a300-bddbc8777d26.png)

**Comment by mglesser** [comment]
1. The table 4 from the ECMA 418-2 is a recomendation on the block length and hop size to be used for the computation of the psychoacoustic tonality. In MOSQITO, we have decided to let the user free to use other values. That's why the parameters sb and sh can be provided as lists to the comp_loudness function to specify sb and sh per frequency band. However I have to admit taht this feature hasn't been tested yet.
2. This behavior corresponds to the section 5.1.4 of the standard. I don't like it too much neither, but I prefer to keep it like that until we have the tonality and loudness computation ready. It will then be the time to see if we can change this behavior without impacting the other metrics evaluation.
