### ISSUE TITLE
About Weighting

### ISSUE THREAD

**Issue by rizkyramadh13** [Eomys/MoSQITo#59]
Hello creator, I want to ask you what weighting this mosqito code uses?

**Comment by wantysal** [comment]
Hello,

If you talk about dB-weighting, you can find a method to convert a dB spectrum (ref value 2e-5) to dBA according to CEI 61672:2014. The function is located in mosqito.utils.conversion

Otherwise, the input spectrum for the sound quality metrics calculation must be provided in amplitude or complex (except for loudness that requires RMS spectra). Each metric calculation then includes some specific weightings corresponding to the hearing model.

I hope this answers your question, 
Salomé
