### ISSUE TITLE
Obtaining a single value estimate from roughness_dw

### ISSUE THREAD

**Issue by bthj** [Eomys/MoSQITo#77]
Hi

I'd like to compare if one sound is preceptually more rough than the other: can you recommend an approach for doing that? Would taking an average of the values (R) returned form the roughness_dw function be a viable approach? Wound `mean` be a good average in this case?

Cheers
/Björn

**Comment by wantysal** [comment]
Hi Björn,

This is an interesting question. The reference article doesn't specify a method to get a single value per sound. There are several approaches commonly used in psychoacoustics studies to do it : 
 * if the signal is (quasi-)stationnary, you can use the mean value
 * if the signal is time-varying, using the mean value presents a risk of smoothing some information that is significant to compare your signals... The median is a better option since it is less affected by extreme values. The 95-th percentile value gives better results to do some comparisons though.
 
I think the best option is to compute several statistics indicators (mean, median, percentiles...) and try to see which one gives better results, since it depends on the nature of your sounds ;)

Salomé

**Comment by bthj** [comment]
Thanks for the suggestions, Salomé - I'll compare those statistics indicators.

The plan is to examine the suitability of roughness as a general metric for the quality of synthesised sounds, which are time-varying. I've also considered a [roughness (sensory dissonance) metric function](https://www.jyu.fi/hytk/fi/laitokset/mutku/en/research/materials/mirtoolbox/MIRtoolbox%20Users%20Guide%201.3.2#page=109) from the [MIRtoolbox](https://www.jyu.fi/hytk/fi/laitokset/mutku/en/research/materials/mirtoolbox), but Matlab is less accessible in my experimental setup. The description of that MIRtoolbox function references [Plomp and Levelt (1965)](https://www.mpi.nl/world/materials/publications/levelt/Plomp_Levelt_Tonal_1965.pdf), while your implementaion references [Daniel and Weber, 1997](https://www.ingentaconnect.com/content/dav/aaua/1997/00000083/00000001/art00020), where the latter does reference the former: can it be considered as an improvement on Plomp and Levelt's work? - or in any case compared as apples and apples, rather than apples and oranges?
